name: Scheduled Task

on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "This is a scheduled job running every 30 minutes."

      # Future steps can be added here.
      # For example, to checkout the repository:
      # - uses: actions/checkout@v3

      # It's a good practice to use secrets for sensitive information.
      # For example, if you need to use an API token:
      # - name: Use secret
      #   env:
      #     API_TOKEN: ${{ secrets.API_TOKEN }}
      #   run: |
      #     # Your script that uses the API token
      #     echo "Using the API token securely."
